[package]
name = "test_winrt"
version = "0.1.0"
authors = ["iuill"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winrt = { git = "https://github.com/microsoft/winrt-rs" }
bindings = { path = "bindings" }
